'use client';
import Link from 'next/link';
import { useState } from 'react';
import { Sparkles, ArrowRight } from 'lucide-react';
import { useData } from './provider';
import { PageHeader } from './ui';
import { operatingAssistant, type AiAnswer } from '@/services/ai';
const actions=['오늘 매출','어제 비교','이번주 매출','판매 TOP','재고부족','발주추천','이번달 예상매출','예상정산'];
export function AiScreen(){const {state,session}=useData(),[input,setInput]=useState(''),[prompt,setPrompt]=useState('오늘 매장 브리핑'),[answer,setAnswer]=useState<AiAnswer>(()=>operatingAssistant(state,session.storeId,'오늘 브리핑'));function ask(text:string){if(!text.trim())return;setPrompt(text);setAnswer(operatingAssistant(state,session.storeId,text));setInput('');}return <><PageHeader title="뜬금AI" description="숫자를 읽고, 오늘의 운영을 함께 준비하는 매장 비서"/><section className="assistant-intro"><span className="ai-symbol"><Sparkles/></span><div><h2>무엇부터 확인해 볼까요?</h2><p>매출 · 재고 · 발주 · 정산을 바로 확인해 드려요.</p></div></section><div className="quick-actions">{actions.map(a=><button className="chip" key={a} onClick={()=>ask(a)}>{a}</button>)}</div><form className="assistant-input" onSubmit={e=>{e.preventDefault();ask(input);}}><input aria-label="운영 질문" value={input} onChange={e=>setInput(e.target.value)} placeholder="오늘 뭐 발주해야 해?" required maxLength={500}/><button className="button" aria-label="질문 확인"><ArrowRight size={19}/></button></form><section className="panel assistant-answer" aria-live="polite"><div className="panel-heading"><h2><Sparkles size={20}/> 운영 브리핑</h2><span className="badge blue">{state.production?'운영 데이터 분석':'규칙 기반 데모'}</span></div><p className="question-label">{prompt}</p><h3>{answer.text}</h3><div>{answer.details.map((d,i)=><div className="answer-item" key={i}>{d}</div>)}</div>{answer.href&&<Link className="button" href={answer.href}>{answer.linkLabel}</Link>}</section><p className="muted small">외부 AI API를 사용하지 않습니다. {state.production?'현재 운영 데이터를 기반으로 계산한 안내입니다. 자동으로 발주를 확정하지 않습니다.':'현재 데모 데이터를 기반으로 계산한 안내입니다.'}</p></>;}
