'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useData } from './provider';
import { DataTable, EmptyState, ErrorState, FilterChip, Modal, PageHeader, Panel, StatusBadge } from './ui';
import { ticketCategories } from '@/data/mock';
import { today } from '@/lib/calculations';
import type { SupportTicket } from '@/types/domain';
export function NoticesScreen({hq}:{hq:boolean}){
 const {state,session,execute,busy}=useData(),[filter,setFilter]=useState('전체'),[selected,setSelected]=useState<string|null>(null),[compose,setCompose]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[important,setImportant]=useState(false),[error,setError]=useState('');
 const read=(id:string)=>state.noticeReads.includes(`${session.profile.id}:${id}`),notices=state.notices.filter(n=>filter==='전체'||filter==='중요공지'&&n.important||filter==='안읽음'&&!read(n.id));
 async function open(id:string){setError('');setSelected(id);try{await execute({type:'readNotice',noticeId:id});}catch(e){setError(e instanceof Error?e.message:'읽음 처리에 실패했습니다.');}}
 async function publish(e:React.FormEvent){e.preventDefault();setError('');try{await execute({type:'notice',title,body,important});setCompose(false);setTitle('');setBody('');setImportant(false);}catch(e){setError(e instanceof Error?e.message:'등록에 실패했습니다.');}}
 const notice=state.notices.find(n=>n.id===selected);
 return <><PageHeader title={hq?'공지사항':'본사공지'} description="본사에서 전하는 운영 소식을 확인하세요." action={hq?<button className="button" onClick={()=>setCompose(true)}>+ 공지 작성</button>:undefined}/><div className="filters">{['전체','중요공지','안읽음'].map(f=><FilterChip key={f} active={f===filter} onClick={()=>setFilter(f)}>{f}</FilterChip>)}</div>{error&&<ErrorState message={error}/>}<section className="panel notice-list">{notices.map(n=><button key={n.id} className="notice-row" onClick={()=>void open(n.id)}><div>{n.important&&<span className="badge warning">중요</span>}<strong>{n.title}</strong><small>{n.createdAt}</small></div><span className={`badge ${read(n.id)?'neutral':'blue'}`}>{read(n.id)?'읽음':'안읽음'}</span></button>)}{!notices.length&&<EmptyState/>}</section>{notice&&<Modal title={notice.title} onClose={()=>setSelected(null)}><p className="muted small">{notice.createdAt}</p><p className="notice-body">{notice.body}</p></Modal>}{compose&&<Modal title="공지 작성" onClose={()=>setCompose(false)}><form onSubmit={publish}><label>제목<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>내용<textarea rows={5} value={body} onChange={e=>setBody(e.target.value)} required/></label><label className="check-label"><input type="checkbox" checked={important} onChange={e=>setImportant(e.target.checked)}/>중요공지</label>{error&&<ErrorState message={error}/>}<button className="button" disabled={busy}>공지 등록</button></form></Modal>}</>;
}
function TicketForm({ticket,hq,onClose}:{ticket:SupportTicket;hq:boolean;onClose:()=>void}){const {state,execute,busy}=useData(),[draft,setDraft]=useState(ticket),[error,setError]=useState(''),existing=state.tickets.some(t=>t.id===ticket.id);async function save(e:React.FormEvent){e.preventDefault();try{await execute({type:'ticket',ticket:draft});onClose();}catch(e){setError(e instanceof Error?e.message:'저장에 실패했습니다.');}}return <Modal title={existing?'문의 상세':'본사 문의하기'} onClose={onClose}><form onSubmit={save}>{existing?<><h3>{ticket.title}</h3><p className="muted">{ticket.category} · {ticket.createdAt}</p><p className="notice-body">{ticket.body}</p></>:<><label>카테고리<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value as SupportTicket['category']})}>{ticketCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>제목<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} required/></label><label>내용<textarea value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} required rows={4}/></label></>}{existing&&hq?<><label>처리 상태<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as SupportTicket['status']})}>{['접수','처리중','답변완료','종료'].map(s=><option key={s}>{s}</option>)}</select></label><label>답변<textarea rows={4} value={draft.answer} onChange={e=>setDraft({...draft,answer:e.target.value})}/></label></>:existing&&<div className="info-box"><strong>본사 답변</strong><p>{ticket.answer||'답변을 준비 중입니다.'}</p></div>}{error&&<ErrorState message={error}/>}<div className="actions">{(!existing||hq)&&<button className="button" disabled={busy}>{existing?'답변 저장':'문의 접수'}</button>}<button type="button" className="button secondary" onClick={onClose}>닫기</button></div></form></Modal>;}
export function SupportScreen({hq}:{hq:boolean}){const {state,session}=useData(),[status,setStatus]=useState('전체'),[category,setCategory]=useState('전체'),[selected,setSelected]=useState<SupportTicket|null>(null),tickets=state.tickets.filter(t=>(hq||t.storeId===session.storeId)&&(status==='전체'||status===t.status)&&(category==='전체'||category===t.category));return <><PageHeader title={hq?'문의관리':'본사문의'} description="매장 운영의 궁금한 점을 본사와 해결하세요." action={!hq?<button className="button" onClick={()=>setSelected({id:crypto.randomUUID(),storeId:session.storeId,title:'',body:'',category:'발주',status:'접수',answer:'',createdAt:today()})}>+ 문의하기</button>:undefined}/><div className="toolbar"><div className="filters">{['전체','접수','처리중','답변완료','종료'].map(s=><FilterChip key={s} active={status===s} onClick={()=>setStatus(s)}>{s}</FilterChip>)}</div><select aria-label="문의 카테고리" value={category} onChange={e=>setCategory(e.target.value)}>{['전체',...ticketCategories].map(c=><option key={c}>{c}</option>)}</select></div><Panel title={`문의 ${tickets.length}건`}><DataTable rows={tickets} keyOf={t=>t.id} columns={[{label:'제목',render:t=><button className="text-link" onClick={()=>setSelected(t)}>{t.title}</button>},{label:'매장',render:t=>state.stores.find(s=>s.id===t.storeId)?.name},{label:'카테고리',render:t=>t.category},{label:'접수일',render:t=>t.createdAt},{label:'상태',render:t=><StatusBadge status={t.status}/>} ]}/></Panel>{selected&&<TicketForm key={selected.id} ticket={selected} hq={hq} onClose={()=>setSelected(null)}/>}</>;}
export function NotificationsScreen(){const {state,session,execute,busy}=useData(),[filter,setFilter]=useState('전체'),[error,setError]=useState(''),items=state.notifications.filter(n=>n.storeId===session.storeId&&(filter==='전체'||!n.read));async function mark(id:string){try{await execute({type:'readNotification',notificationId:id});}catch(e){setError(e instanceof Error?e.message:'읽음 처리에 실패했습니다.');}}return <><PageHeader title="알림" description="놓치지 말아야 할 매장 소식을 모았어요."/><div className="filters">{['전체','안읽음'].map(f=><FilterChip key={f} active={f===filter} onClick={()=>setFilter(f)}>{f}</FilterChip>)}</div>{error&&<ErrorState message={error}/>}<div className="notification-list">{items.map(n=><article className={`panel notification-item ${n.read?'':'unread'}`} key={n.id}><div className="split"><span className="badge blue">{n.type}</span><span className="muted small">{n.createdAt}</span></div><h2>{n.title}</h2><p className="muted">{n.body}</p><div className="split"><Link className="text-link" href={n.href} onClick={()=>void mark(n.id)}>내용 확인 →</Link>{!n.read?<button className="text-link" disabled={busy} onClick={()=>void mark(n.id)}>읽음 처리</button>:<span className="muted small">읽음</span>}</div></article>)}</div>{!items.length&&<EmptyState title="새로운 알림이 없습니다."/>}</>;}
