'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useData } from './provider';
import { DataTable, EmptyState, ErrorState, FilterChip, KpiCard, PageHeader, Panel, SearchInput, StatusBadge } from './ui';
import { number, reorderFor } from '@/lib/calculations';
import type { Product } from '@/types/domain';
export function InventoryCard({product,storeId,hq}:{product:Product;storeId:string;hq:boolean}){const {state}=useData(),item=reorderFor(state,storeId,product);return <Link className="inventory-card" href={`${hq?'/hq':'/store'}/inventory/${product.id}${hq?`?store=${storeId}`:''}`}><div className="split"><span className="muted small">{product.category}</span><StatusBadge status={item.status}/></div><h2>{product.name}</h2><p className="stock-number">{item.currentStock}<small>개 남음</small></p><div className="inventory-metrics"><span>안전재고 <b>{product.safetyStock}</b></span><span>권장재고 <b>{product.recommendedStock}</b></span><span>예상소진 <b>{item.daysUntilStockout===null?'판매 없음':`${number(item.daysUntilStockout)}일`}</b></span></div></Link>;}
export function InventoryScreen({hq}:{hq:boolean}){
 const {state,session}=useData(),params=useSearchParams(),[store,setStore]=useState(params.get('store')||session.storeId),[filter,setFilter]=useState('전체'),[search,setSearch]=useState('');const storeId=hq?store:session.storeId;
 const items=state.products.filter(p=>p.name.includes(search)||p.sku.includes(search)).filter(p=>filter==='전체'||reorderFor(state,storeId,p).status===filter);
 return <><PageHeader title="재고관리" description="재고 위험을 먼저 확인하고 필요한 상품을 발주하세요." action={!hq?<Link className="button" href="/store/reorder">자동발주 추천</Link>:undefined}/><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="상품명 또는 SKU 검색"/>{hq&&<select value={store} onChange={e=>setStore(e.target.value)} aria-label="재고 매장 선택">{state.stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}</div><div className="filters">{['전체','정상','주의','부족','품절'].map(f=><FilterChip key={f} active={f===filter} onClick={()=>setFilter(f)}>{f}</FilterChip>)}</div><div className="inventory-grid">{items.map(p=><InventoryCard key={p.id} product={p} storeId={storeId} hq={hq}/>)}</div>{!items.length&&<EmptyState/>}</>;
}
export function InventoryDetail({productId,hq}:{productId:string;hq:boolean}){
 const {state,session,execute,busy}=useData(),params=useSearchParams(),router=useRouter(),storeId=hq?(params.get('store')||session.storeId):session.storeId,product=state.products.find(p=>p.id===productId),[quantity,setQuantity]=useState('0'),[reason,setReason]=useState(''),[error,setError]=useState(''),[feedback,setFeedback]=useState('');
 if(!product)return <EmptyState title="상품을 찾을 수 없습니다."/>;const item=reorderFor(state,storeId,product);
 async function adjust(e:React.FormEvent){e.preventDefault();setError('');setFeedback('');if(hq&&storeId!==session.storeId){setError('다른 매장의 재고조정은 해당 매장 계정으로 진행해 주세요.');return;}try{await execute({type:'adjustInventory',productId,quantity:Number(quantity),reason});setFeedback('재고가 조정되었습니다.');setQuantity('0');setReason('');}catch(e){setError(e instanceof Error?e.message:'조정에 실패했습니다.');}}
 return <><PageHeader title={product.name} description={`${product.sku} · ${state.stores.find(s=>s.id===storeId)?.name}`} action={<button className="button secondary" onClick={()=>router.back()}>목록으로</button>}/><div className="kpi-grid four"><KpiCard label="현재재고" value={`${item.currentStock}개`}/><KpiCard label="안전재고" value={`${product.safetyStock}개`}/><KpiCard label="권장재고" value={`${product.recommendedStock}개`}/><KpiCard label="예상소진일" value={item.daysUntilStockout===null?'판매 없음':`${number(item.daysUntilStockout)}일`}/></div><div className="dashboard-grid"><Panel title="최근 판매량"><div className="list-row"><span>최근 14일 판매량</span><strong>{item.recent14DaySales}개</strong></div><div className="list-row"><span>일평균 판매</span><strong>{number(item.averageDailySales)}개</strong></div><div className="list-row"><span>미입고 발주</span><strong>{item.outstandingOrderQuantity}개</strong></div><div className="list-row"><span>상태</span><StatusBadge status={item.status}/></div>{!hq&&<Link className="button full" href={`/store/reorder?product=${productId}`}>발주하기</Link>}</Panel><Panel title="재고조정"><form onSubmit={adjust}><label>조정 수량 (추가 + / 차감 −)<input type="number" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label>조정 사유<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="실사, 파손 등" required/></label>{error&&<ErrorState message={error}/>}<button className="button" disabled={busy||hq&&storeId!==session.storeId}>재고조정 저장</button>{feedback&&<p role="status" className="positive">{feedback}</p>}{hq&&storeId!==session.storeId&&<p className="muted small">다른 매장 재고는 조회만 가능합니다.</p>}</form></Panel></div><Panel title="재고이력"><DataTable rows={state.inventoryTransactions.filter(t=>t.storeId===storeId&&t.productId===productId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))} keyOf={r=>r.id} columns={[{label:'일시',render:r=>new Date(r.createdAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})},{label:'사유',render:r=>r.reason},{label:'변동',render:r=>`${r.quantity>0?'+':''}${r.quantity}개`},{label:'재고',render:r=>`${r.before} → ${r.after}`} ]}/></Panel></>;
}
