'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, Store, Building2, ShieldCheck } from 'lucide-react';
import { useApp } from './provider';
import { ErrorState, Modal, TteungeumOnLogo } from './ui';
import { isHq } from '@/services/service';
export function LoginScreen(){
 const {login,session,ready,mode,error:storageError}=useApp(),router=useRouter();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[remember,setRemember]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[help,setHelp]=useState(false);
 useEffect(()=>{if(ready&&session)router.replace(isHq(session)?'/hq':'/store');},[ready,session,router]);
 async function signIn(kind:'hq'|'store'|null){setBusy(true);setError('');try{const user=await login(kind,email,password,remember);router.replace(isHq(user)?'/hq':'/store');}catch(e){setError(e instanceof Error?e.message:'로그인에 실패했습니다.');}finally{setBusy(false);}}
 return <main className="login-page"><section className="login-story"><TteungeumOnLogo/><div><span className="story-tag">우리 매장의 새로운 일상</span><h1>매장을 더<br/>똑똑하게 <span>ON</span></h1><p>매출부터 재고, 발주까지.<br/>본사와 매장을 잇는 든든한 운영 파트너.</p><div className="story-stats"><span><Store/>매장 운영</span><span><ShieldCheck/>본사와 연결</span></div></div><small>뜬금상점 통합 점포관리 시스템</small></section><section className="login-form-section"><div className="login-card"><div className="mobile-logo"><TteungeumOnLogo/></div><p className="eyebrow">WELCOME BACK</p><h2>반가워요!</h2><p className="muted">매장을 더 똑똑하게 ON</p><form onSubmit={e=>{e.preventDefault();void signIn(null);}}><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="이메일을 입력해 주세요" autoComplete="username" required/></label><label>비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="비밀번호를 입력해 주세요" autoComplete="current-password" required/></label><div className="split"><label className="check-label"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>로그인 상태 유지</label><button className="text-link" type="button" onClick={()=>setHelp(true)}>비밀번호 찾기</button></div>{(error||storageError)&&<ErrorState message={error||storageError}/>}<button className="button full" disabled={busy||!ready||!!storageError}>{busy?'로그인 중…':'로그인'}<ArrowRight size={18}/></button></form>{mode==='mock'&&<div className="demo-login"><p>먼저 둘러보세요</p><div className="demo-buttons"><button className="button secondary" disabled={busy||!ready||!!storageError} onClick={()=>void signIn('hq')}><Building2 size={17}/>본사 데모 로그인</button><button className="button secondary" disabled={busy||!ready||!!storageError} onClick={()=>void signIn('store')}><Store size={17}/>점주 데모 로그인</button></div><small>실제 인증 전 데모 환경입니다. 데이터는 이 브라우저에 저장됩니다.</small></div>}</div></section>{help&&<Modal title={mode==='mock'?"데모 로그인 안내":"계정 도움말"} onClose={()=>setHelp(false)}><p>{mode==='mock'?"실제 비밀번호 재설정은 Supabase 연결 후 제공됩니다.":"계정 또는 비밀번호 변경은 본사 관리자에게 요청해 주세요."}</p>{mode==='mock'&&<div className="info-box"><p>본사: hq@tteungeum.demo</p><p>점주: owner@tteungeum.demo</p><p>공통 비밀번호: Demo1234!</p></div>}</Modal>}</main>;
}
