'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Bell, Megaphone, MessageCircle, Wallet, ClipboardList, Sparkles, Settings, CircleHelp, LogOut, ChevronRight } from 'lucide-react';
import { useData } from './provider';
import { DataTable, PageHeader, Panel, SearchInput, StatusBadge } from './ui';
export function StoresScreen(){const {state}=useData(),[search,setSearch]=useState('');return <><PageHeader title="매장관리" description="함께 성장하는 직영점과 가맹점을 확인하세요."/><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="매장명 또는 점주 검색"/></div><Panel title={`전체 ${state.stores.length}개 매장`}><DataTable rows={state.stores.filter(s=>s.name.includes(search)||s.owner.includes(search))} keyOf={s=>s.id} columns={[{label:'매장명',render:s=>s.name},{label:'운영 형태',render:s=>s.type},{label:'점주',render:s=>s.owner},{label:'주소',render:s=>s.address},{label:'운영 상태',render:s=><StatusBadge status={s.active?'운영중':'운영중지'}/>},{label:'재고 확인',render:s=><Link className="text-link" href={`/hq/inventory?store=${s.id}`}>매장 재고 →</Link>} ]}/></Panel></>;}
export function MoreScreen(){const {state,session,logout}=useData(),router=useRouter(),store=state.stores.find(s=>s.id===session.storeId);const links=[['notices','본사공지',Megaphone],['support','본사문의',MessageCircle],['notifications','알림',Bell],['settlements','정산',Wallet],['orders','발주내역',ClipboardList],['ai','뜬금AI',Sparkles],['settings','매장설정',Settings],['help','도움말',CircleHelp]] as const;return <><PageHeader title="더보기" description="매장 운영에 필요한 모든 메뉴"/><section className="panel profile-card"><div className="avatar large">{session.profile.name.slice(0,1)}</div><div><h2>{session.profile.name} 점주님</h2><p className="muted">{store?.name}</p></div></section><section className="panel more-menu">{links.map(([key,label,Icon])=><Link key={key} href={`/store/${key}`}><span><Icon size={21}/>{label}</span><ChevronRight size={18}/></Link>)}<button onClick={async()=>{await logout();router.replace('/login');}}><span><LogOut size={21}/>로그아웃</span></button></section></>;}
export function SettingsScreen(){const {state,session}=useData(),store=state.stores.find(s=>s.id===session.storeId);return <><PageHeader title="매장설정" description="현재 연결된 매장의 정보입니다."/><Panel title="매장 기본정보"><div className="list-row"><span>매장명</span><strong>{store?.name}</strong></div><div className="list-row"><span>주소</span><strong>{store?.address}</strong></div><div className="list-row"><span>운영 형태</span><strong>{store?.type}</strong></div><div className="list-row"><span>점주</span><strong>{store?.owner}</strong></div><div className="list-row"><span>계정</span><strong>{session.profile.email}</strong></div><p className="muted small mt">매장 정보 변경과 멤버 초대는 Supabase 연결 후 제공할 예정입니다.</p></Panel></>;}
export function HelpScreen(){return <><PageHeader title="도움말" description="뜬금ON을 처음 사용하시나요?"/><Panel title="발주 신청 방법"><ol className="help-list"><li>재고관리에서 부족한 상품을 확인하세요.</li><li>자동발주 추천에서 수량을 조정하고 발주서에 담으세요.</li><li>발주서에서 VAT 포함 금액을 확인하고 신청하세요.</li><li>발주내역에서 승인과 배송 상태를 확인하세요.</li></ol><Link className="button" href="/store/reorder">자동발주 시작하기</Link></Panel><Panel title="데모 안내"><p>데모 데이터는 현재 브라우저에 저장됩니다. 로그아웃 후 본사 데모 로그인으로 발주를 승인할 수 있습니다. 실제 인증, 서버 저장, 외부 AI 및 결제는 연결되지 않았습니다.</p></Panel></>;}
