'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Trash2 } from 'lucide-react';
import { useData } from './provider';
import { ConfirmDialog, DataTable, EmptyState, ErrorState, FilterChip, Money, PageHeader, Panel, QuantityControl, StatusBadge } from './ui';
import { money, orderLabels } from '@/lib/calculations';
import { allowedOrderTransitions } from '@/services/service';
import type { OrderStatus, PurchaseOrder } from '@/types/domain';
export function OrderCard({order,hq}:{order:PurchaseOrder;hq:boolean}){const {state}=useData();return <Link className="order-card" href={`${hq?'/hq':'/store'}/orders/${order.id}`}><div className="split"><strong>{order.number}</strong><StatusBadge status={order.status}/></div><p className="muted">{state.stores.find(s=>s.id===order.storeId)?.name}</p><div className="split"><span className="muted small">{order.createdAt.slice(0,10)}</span><strong><Money value={order.total}/></strong></div></Link>;}
export function OrdersScreen({hq}:{hq:boolean}){const {state,session}=useData(),[status,setStatus]=useState('ALL'),orders=state.orders.filter(o=>(hq||o.storeId===session.storeId)&&(status==='ALL'||o.status===status));return <><PageHeader title={hq?'본사 발주관리':'발주내역'} description="신청부터 입고까지, 진행 상태를 확인하세요." action={!hq?<Link className="button" href="/store/reorder">새 발주 만들기</Link>:undefined}/><div className="filters"><FilterChip active={status==='ALL'} onClick={()=>setStatus('ALL')}>전체</FilterChip>{Object.entries(orderLabels).map(([key,label])=><FilterChip key={key} active={status===key} onClick={()=>setStatus(key)}>{label}</FilterChip>)}</div>{hq?<Panel title={`발주 ${orders.length}건`}><DataTable rows={orders} keyOf={o=>o.id} columns={[{label:'발주번호',render:o=><Link className="text-link" href={`/hq/orders/${o.id}`}>{o.number}</Link>},{label:'매장',render:o=>state.stores.find(s=>s.id===o.storeId)?.name},{label:'신청일',render:o=>o.createdAt.slice(0,10)},{label:'금액',render:o=><Money value={o.total}/>},{label:'상태',render:o=><StatusBadge status={o.status}/>} ]}/></Panel>:<div className="order-grid">{orders.map(o=><OrderCard key={o.id} order={o} hq={false}/>)}</div>}{!hq&&!orders.length&&<EmptyState title="발주내역이 없습니다."/>}</>;}
export function NewOrderScreen(){
 const {state,session,execute,busy}=useData(),router=useRouter(),[note,setNote]=useState(''),[confirm,setConfirm]=useState(false),[error,setError]=useState('');const cart=state.carts[session.storeId]||[],rows=cart.map(i=>({...i,product:state.products.find(p=>p.id===i.productId)!})),supply=rows.reduce((n,i)=>n+i.quantity*i.product.supplyPrice,0),vat=Math.round(supply*.1);
 async function update(productId:string,quantity:number){setError('');try{await execute({type:'cart',items:quantity===0?cart.filter(i=>i.productId!==productId):cart.map(i=>i.productId===productId?{...i,quantity}:i)});}catch(e){setError(e instanceof Error?e.message:'수량 변경에 실패했습니다.');}}
 async function submit(){setError('');try{await execute({type:'submitOrder',note});setConfirm(false);router.push('/store/orders');}catch(e){setConfirm(false);setError(e instanceof Error?e.message:'신청에 실패했습니다.');}}
 return <><PageHeader title="발주서 만들기" description="수량과 금액을 확인한 뒤 신청해 주세요."/>{error&&<ErrorState message={error}/>}<div className="checkout-grid"><Panel title={`발주 상품 ${cart.length}개`}><DataTable rows={rows} keyOf={i=>i.productId} empty="담긴 상품이 없습니다." columns={[{label:'상품',render:i=>i.product.name},{label:'수량',render:i=><QuantityControl value={i.quantity} label={`${i.product.name} 발주수량`} disabled={busy} onChange={q=>void update(i.productId,q)}/>},{label:'단가',render:i=><Money value={i.product.supplyPrice}/>},{label:'금액',render:i=><Money value={i.quantity*i.product.supplyPrice}/>},{label:'삭제',render:i=><button className="icon-button" disabled={busy} aria-label={`${i.product.name} 삭제`} onClick={()=>void update(i.productId,0)}><Trash2 size={18}/></button>} ]}/><Link className="text-link" href="/store/reorder">+ 추천상품 추가</Link><label className="mt">요청사항<textarea value={note} maxLength={1000} onChange={e=>setNote(e.target.value)} placeholder="배송 시 요청사항을 적어주세요." rows={3}/></label></Panel><Panel title="발주 금액"><div className="list-row"><span>공급가액</span><Money value={supply}/></div><div className="list-row"><span>VAT (10%)</span><Money value={vat}/></div><div className="list-row total"><strong>총 발주금액</strong><strong><Money value={supply+vat}/></strong></div><button className="button full" onClick={()=>setConfirm(true)} disabled={busy||!cart.length}>발주 신청</button><p className="muted small mt">데모 신청은 이 브라우저에만 저장되며 실제 발주가 전송되지 않습니다.</p></Panel></div>{confirm&&<ConfirmDialog title="발주 신청 확인" description={`${money(supply+vat)}의 발주를 신청하시겠습니까?`} onConfirm={()=>void submit()} onClose={()=>setConfirm(false)} busy={busy}/>}</>;
}
export function OrderDetail({orderId,hq}:{orderId:string;hq:boolean}){
 const {state,session,execute,busy}=useData(),[target,setTarget]=useState<OrderStatus|null>(null),[error,setError]=useState(''),order=state.orders.find(o=>o.id===orderId&&(hq||o.storeId===session.storeId));
 if(!order)return <EmptyState title="발주를 찾을 수 없습니다."/>;
 const rows=state.orderItems.filter(i=>i.orderId===orderId),actions=allowedOrderTransitions(order.status),labels:Partial<Record<OrderStatus,string>>={APPROVED:'승인',PREPARING:'준비중',SHIPPED:'출고',DELIVERED:'배송완료',CANCELLED:'취소'};
 async function change(){if(!target)return;setError('');try{await execute({type:'orderStatus',orderId,status:target});setTarget(null);}catch(e){setTarget(null);setError(e instanceof Error?e.message:'상태 변경에 실패했습니다.');}}
 return <><PageHeader title="발주 상세" description={order.number} action={<Link className="button secondary" href={`${hq?'/hq':'/store'}/orders`}>발주 목록</Link>}/>{error&&<ErrorState message={error}/>}<Panel title={state.stores.find(s=>s.id===order.storeId)?.name||'매장'}><div className="split"><p className="muted">신청일 {new Date(order.createdAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p><StatusBadge status={order.status}/></div><DataTable rows={rows} keyOf={i=>i.id} columns={[{label:'상품명',render:i=>state.products.find(p=>p.id===i.productId)?.name},{label:'수량',render:i=>`${i.quantity}개`},{label:'단가',render:i=><Money value={i.unitPrice}/>},{label:'금액',render:i=><Money value={i.quantity*i.unitPrice}/>} ]}/><div className="order-summary"><p>공급가액 <Money value={order.supplyAmount}/></p><p>VAT <Money value={order.vat}/></p><strong>총 발주금액 <Money value={order.total}/></strong></div><div className="info-box"><strong>요청사항</strong><p>{order.note||'없음'}</p></div>{hq&&<div className="actions">{actions.map(status=><button className={`button ${status==='CANCELLED'?'danger-button':''}`} key={status} disabled={busy} onClick={()=>setTarget(status)}>{labels[status]}</button>)}{!actions.length&&<p className="muted">완료된 발주입니다. 더 이상 상태를 변경할 수 없습니다.</p>}</div>}</Panel>{target&&<ConfirmDialog title="발주 상태 변경" description={`${order.number} 발주를 ${orderLabels[target]} 상태로 변경하시겠습니까?${target==='DELIVERED'?' 상품 수량이 매장 재고에 입고됩니다.':''}`} busy={busy} onClose={()=>setTarget(null)} onConfirm={()=>void change()}/>}</>;
}
