'use client';
import { useState } from 'react';
import { useData } from './provider';
import { categories } from '@/data/mock';
import { DataTable, ErrorState, FilterChip, Modal, Money, PageHeader, Panel, SearchInput, StatusBadge } from './ui';
import type { Product } from '@/types/domain';
function blankProduct():Product{return {id:crypto.randomUUID(),sku:'',name:'',category:'커피',cost:0,supplyPrice:0,price:0,safetyStock:12,recommendedStock:80,status:'판매중',supplierId:'supplier-1',leadTimeDays:3};}
function ProductForm({product,onClose}:{product:Product;onClose:()=>void}){const {execute,busy}=useData(),[draft,setDraft]=useState(product),[error,setError]=useState('');const numeric=[['cost','원가'],['supplyPrice','공급가'],['price','판매가'],['safetyStock','안전재고'],['recommendedStock','권장재고'],['leadTimeDays','배송 소요일']] as const;async function save(e:React.FormEvent){e.preventDefault();setError('');try{await execute({type:'product',product:draft});onClose();}catch(e){setError(e instanceof Error?e.message:'저장에 실패했습니다.');}}return <Modal title="상품 등록 / 수정" onClose={onClose}><form onSubmit={save}><div className="form-grid"><label>SKU<input value={draft.sku} onChange={e=>setDraft({...draft,sku:e.target.value})} required/></label><label>상품명<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required/></label><label>카테고리<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value as Product['category']})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>판매상태<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Product['status']})}><option>판매중</option><option>판매중지</option></select></label>{numeric.map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="1" value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})} required/></label>)}</div>{error&&<ErrorState message={error}/>}<div className="actions"><button type="button" className="button secondary" onClick={onClose}>취소</button><button className="button" disabled={busy}>상품 저장</button></div></form></Modal>;}
export function ProductsScreen(){const {state}=useData(),[search,setSearch]=useState(''),[category,setCategory]=useState('전체'),[editing,setEditing]=useState<Product|null>(null),products=state.products.filter(p=>(category==='전체'||p.category===category)&&(p.name.includes(search)||p.sku.toLowerCase().includes(search.toLowerCase())));return <><PageHeader title="상품관리" description="상품의 가격과 재고 기준을 관리합니다." action={<button className="button" onClick={()=>setEditing(blankProduct())}>+ 상품등록</button>}/><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="상품명 또는 SKU 검색"/><span className="muted small">총 {products.length}개 상품</span></div><div className="filters">{['전체',...categories].map(c=><FilterChip key={c} active={category===c} onClick={()=>setCategory(c)}>{c}</FilterChip>)}</div><Panel title="상품 목록"><DataTable rows={products} keyOf={p=>p.id} columns={[{label:'SKU',render:p=>p.sku},{label:'상품명',render:p=><button className="text-link" onClick={()=>setEditing(p)}>{p.name}</button>},{label:'카테고리',render:p=>p.category},{label:'원가',render:p=><Money value={p.cost}/>},{label:'공급가',render:p=><Money value={p.supplyPrice}/>},{label:'판매가',render:p=><Money value={p.price}/>},{label:'안전 / 권장',render:p=>`${p.safetyStock} / ${p.recommendedStock}`},{label:'상태',render:p=><StatusBadge status={p.status}/>} ]}/></Panel>{editing&&<ProductForm key={editing.id} product={editing} onClose={()=>setEditing(null)}/>}</>;}
