'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { Sparkles, Check } from 'lucide-react';
import { useData } from './provider';
import { EmptyState, ErrorState, Money, PageHeader, QuantityControl, StatusBadge } from './ui';
import { number, reorderFor } from '@/lib/calculations';
import type { Product } from '@/types/domain';
export function ReorderCard({product,onAdd}:{product:Product;onAdd:(productId:string,quantity:number)=>Promise<void>}){const {state,session,busy}=useData(),result=reorderFor(state,session.storeId,product),[quantity,setQuantity]=useState(Math.max(1,result.orderQuantity)),[added,setAdded]=useState(false),[error,setError]=useState('');return <article className="reorder-card"><div className="split"><span className="muted small">{product.category}</span><StatusBadge status={result.status}/></div><h2>{product.name}</h2><div className="reorder-metrics"><div><span>현재재고</span><strong>{result.currentStock}개</strong></div><div><span>일평균판매</span><strong>{number(result.averageDailySales)}개</strong></div><div><span>예상소진일</span><strong>{result.daysUntilStockout===null?'판매 없음':`${number(result.daysUntilStockout)}일`}</strong></div><div><span>안전재고</span><strong>{result.safetyStock}개</strong></div></div><p className="recommendation">추천수량 <strong>{result.orderQuantity}개</strong></p><p className="muted small">{state.production?'안전재고 기준과 목표재고 부족분을 반영한 제안입니다. 검토 후 직접 발주해 주세요.':<>최근 14일 판매와 배송 소요일 {product.leadTimeDays}일, 안전재고를 반영했어요. 미입고 {result.outstandingOrderQuantity}개를 제외한 수량입니다.</>}</p><div className="split order-controls"><QuantityControl value={quantity} onChange={n=>{setQuantity(n);setAdded(false);}} label={`${product.name} 수량`}/><strong><Money value={quantity*product.supplyPrice}/></strong></div>{error&&<ErrorState message={error}/>}<button className="button full" disabled={busy} onClick={async()=>{setError('');try{await onAdd(product.id,quantity);setAdded(true);}catch(e){setError(e instanceof Error?e.message:'담기에 실패했습니다.');}}}>{added?<><Check size={17}/>담았어요 · 추가 담기</>:'발주담기'}</button></article>;}
export function ReorderScreen(){
 const {state,session,execute,busy}=useData(),params=useSearchParams(),[feedback,setFeedback]=useState(''),[error,setError]=useState('');const selected=params.get('product'),all=state.products.filter(p=>p.status==='판매중'),recommendations=all.filter(p=>reorderFor(state,session.storeId,p).orderQuantity>0),items=selected?all.filter(p=>p.id===selected):recommendations,cart=state.carts[session.storeId]||[];
 async function add(productId:string,quantity:number){const updated=cart.map(i=>({...i})),existing=updated.find(i=>i.productId===productId);if(existing)existing.quantity+=quantity;else updated.push({productId,quantity});await execute({type:'cart',items:updated});setFeedback('발주서에 상품을 담았습니다.');}
 async function suggest(){setError('');try{await execute({type:'suggestOrders',key:crypto.randomUUID()});setFeedback('자동발주 제안을 생성했습니다. 발주내역에서 확인하세요.');}catch(e){setError(e instanceof Error?e.message:'제안 생성 실패');}}
 async function addAll(){setError('');try{const updated=cart.map(i=>({...i}));for(const p of recommendations){const q=reorderFor(state,session.storeId,p).orderQuantity,existing=updated.find(i=>i.productId===p.id);if(existing)existing.quantity=q;else updated.push({productId:p.id,quantity:q});}await execute({type:'cart',items:updated});setFeedback(`${recommendations.length}개 상품을 추천수량으로 담았습니다.`);}catch(e){setError(e instanceof Error?e.message:'담기에 실패했습니다.');}}
 return <><PageHeader title="자동발주 추천" description="판매 흐름을 읽고, 필요한 만큼만 준비하세요." action={<Link className="button" href="/store/orders/new">발주서 만들기 ({cart.length})</Link>}/><div className="info-box split"><div><Sparkles size={22}/><strong>{recommendations.length}개 상품의 발주를 추천해요</strong><p>{state.production?'현재고 ≤ 안전재고 상품만 추천합니다. 추천수량은 권장발주수량과 목표재고 부족분 중 큰 값이며 진행중 발주가 있으면 제외합니다.':'추천수량 = 올림(일평균판매 × 배송 소요일 + 안전재고 − 현재재고 − 미입고 발주)'}</p><small>금액은 공급가 기준이며 VAT는 발주서에서 계산합니다.</small></div><button className="button secondary" disabled={busy||!recommendations.length} onClick={()=>void addAll()}>추천상품 전체 담기</button></div>{feedback&&<p className="positive" role="status">{feedback}</p>}{error&&<ErrorState message={error}/>}<>{state.production&&<button className="button secondary mt" disabled={busy||!recommendations.length} onClick={()=>void suggest()}>자동발주 제안 생성 (승인대기)</button>}</><div className="inventory-grid">{items.map(p=><ReorderCard key={p.id} product={p} onAdd={add}/>)}</div>{!items.length&&<EmptyState title="지금은 추천발주가 없어요." description="필요한 상품은 재고 상세에서 직접 발주할 수 있습니다." action={<Link className="button secondary" href="/store/inventory">재고 살펴보기</Link>}/>}</>;
}
