'use client';
import { useEffect, useState } from 'react';
import { useData } from './provider';
import { ChartCard, DataTable, ErrorState, FilterChip, KpiCard, Money, PageHeader, Panel } from './ui';
import { percentChange, salesSummary, shiftDate, topProducts } from '@/lib/calculations';
export function SalesScreen({hq}:{hq:boolean}){
 const {state,session,refresh}=useData(),[rangeOpen,setRangeOpen]=useState(false),[rangeStart,setRangeStart]=useState(state.generatedOn),[rangeEnd,setRangeEnd]=useState(state.generatedOn),[custom,setCustom]=useState<{start:string;end:string}|null>(null),[rangeError,setRangeError]=useState(''),[rangeBusy,setRangeBusy]=useState(false),[period,setPeriod]=useState('오늘'),[store,setStore]=useState('all');const day=period==='기간 지정'&&custom?custom.end:state.generatedOn,storeId=hq?(store==='all'?null:store):session.storeId;
 const start=period==='기간 지정'&&custom?custom.start:period==='오늘'?day:period==='7일'?shiftDate(day,-6):period==='30일'?shiftDate(day,-29):`${day.slice(0,7)}-01`;
 const count=Math.round((new Date(`${day}T12:00:00Z`).getTime()-new Date(`${start}T12:00:00Z`).getTime())/86400000)+1,previousStart=shiftDate(start,-count),previousEnd=shiftDate(start,-1);
 const current=salesSummary(state,storeId,start,day),previous=salesSummary(state,storeId,previousStart,previousEnd),change=percentChange(current.total,previous.total);
 const points=Array.from({length:count},(_,i)=>{const date=shiftDate(start,i);return {label:date.slice(5),value:salesSummary(state,storeId,date,date).total};}),hours=(state.production?Array.from({length:24},(_,i)=>i):[9,11,13,15,17,19]).map(hour=>({label:`${hour}시`,value:(state.production?(state.periodHours||[]).filter(s=>!storeId||s.storeId===storeId):current.sales).filter(s=>s.hour===hour).reduce((n,s)=>n+s.total,0)}));
 useEffect(()=>()=>{if(state.production)void refresh().catch(()=>{});},[refresh,state.production]);
 async function applyRange(e:React.FormEvent){e.preventDefault();setRangeError('');const days=Math.round((Date.parse(rangeEnd)-Date.parse(rangeStart))/86400000)+1;if(!Number.isFinite(days)||days<1||days>183){setRangeError('시작일과 종료일을 확인하세요. 비교 포함 조회는 최대 183일입니다.');return;}setRangeBusy(true);try{if(state.production)await refresh({start:shiftDate(rangeStart,-days),end:rangeEnd,reportStart:rangeStart,reportEnd:rangeEnd});setCustom({start:rangeStart,end:rangeEnd});setPeriod('기간 지정');}catch(e){setRangeError(e instanceof Error?e.message:'조회 실패');}finally{setRangeBusy(false);}}
 async function changePeriod(p:string){if(!state.production){setPeriod(p);return;}const anchor=state.generatedOn,s=p==='오늘'?anchor:p==='7일'?shiftDate(anchor,-6):p==='30일'?shiftDate(anchor,-29):`${anchor.slice(0,7)}-01`;setRangeError('');setRangeBusy(true);try{await refresh({start:shiftDate(anchor,-61),end:anchor,reportStart:s,reportEnd:anchor});setPeriod(p);}catch(e){setRangeError(e instanceof Error?e.message:'조회 실패');}finally{setRangeBusy(false);}}
 useEffect(()=>{if(state.production)void refresh({start:shiftDate(state.generatedOn,-61),end:state.generatedOn,reportStart:state.generatedOn,reportEnd:state.generatedOn}).catch(()=>{});},[refresh,state.production,state.generatedOn]);
 return <><PageHeader title="매출관리" description={`${start} ~ ${day} · 이전 동일 일수와 비교합니다.`}/><div className="toolbar"><div className="filters">{['오늘','7일','30일','이번달'].map(p=><FilterChip key={p} active={p===period} onClick={()=>{if(!rangeBusy)void changePeriod(p);}}>{p}</FilterChip>)}</div>{hq&&<select aria-label="매장 선택" value={store} onChange={e=>setStore(e.target.value)}><option value="all">전체 매장</option>{state.stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}</div>{state.production&&<><button className="button secondary" onClick={()=>setRangeOpen(!rangeOpen)}>기간 지정</button>{rangeOpen&&<form onSubmit={applyRange} className="panel mt"><div className="form-grid"><label>시작일<input type="date" value={rangeStart} onChange={e=>setRangeStart(e.target.value)} required/></label><label>종료일<input type="date" min={rangeStart} value={rangeEnd} onChange={e=>setRangeEnd(e.target.value)} required/></label></div>{rangeError&&<ErrorState message={rangeError}/>}<button className="button" disabled={rangeBusy}>기간 조회</button></form>}</>}<div className="kpi-grid four"><KpiCard label="총매출" value={<Money value={current.total}/>}/><KpiCard label="주문건수" value={`${current.orders}건`}/><KpiCard label="객단가" value={<Money value={current.average}/>}/><KpiCard label="전기간 대비" value={change===null?'비교 불가':`${change>=0?'+':''}${change.toFixed(1)}%`} hint={`${previousStart} ~ ${previousEnd}`} positive={change!==null&&change>=0}/></div><div className="dashboard-grid"><ChartCard title="기간별 매출" points={points}/><ChartCard title="시간대별 매출" points={hours} kind="bar"/></div>{hq&&<Panel title="매장별 매출"><DataTable rows={state.stores.filter(s=>store==='all'||s.id===store).map(s=>({store:s,...salesSummary(state,s.id,start,day)})).sort((a,b)=>b.total-a.total)} keyOf={r=>r.store.id} columns={[{label:'매장명',render:r=>r.store.name},{label:'총매출',render:r=><Money value={r.total}/>},{label:'판매건수',render:r=>`${r.orders}건`},{label:'객단가',render:r=><Money value={r.average}/>}]}/></Panel>}<Panel title="상품별 판매 TOP"><DataTable rows={topProducts(state,storeId,start,day)} keyOf={r=>r.product.id} columns={[{label:'상품명',render:r=>r.product.name},{label:'카테고리',render:r=>r.product.category},{label:'판매량',render:r=>`${r.quantity}개`},{label:'판매금액',render:r=><Money value={r.amount}/>} ]}/></Panel></>;
}
