'use client';
import { useState } from 'react';
import { useData } from './provider';
import { ErrorState, Modal } from './ui';
import type { Settlement } from '@/types/domain';
import { monthKey } from '@/lib/calculations';
export function SettlementForm({settlement,onClose}:{settlement?:Settlement;onClose:(month?:string)=>void}){
 const {state,execute,busy}=useData(),[storeId,setStoreId]=useState(settlement?.storeId||state.stores[0]?.id||''),[start,setStart]=useState(settlement?.periodStart||`${monthKey()}-01`),[end,setEnd]=useState(settlement?.periodEnd||state.generatedOn),[status,setStatus]=useState(settlement?.dbStatus||'DRAFT'),[adjustment,setAdjustment]=useState(settlement?.adjustment||0),[memo,setMemo]=useState(settlement?.memo||''),[policy,setPolicy]=useState({franchiseFee:0,platformFee:0,otherFee:0}),[error,setError]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();try{if(settlement)await execute({type:'updateSettlement',id:settlement.id,status,adjustment,memo});else await execute({type:'generateSettlement',storeId,start,end,policy:{...policy,adjustment}});onClose(start.slice(0,7));}catch(e){setError(e instanceof Error?e.message:'정산 저장 실패');}}
 return <Modal title={settlement?'정산 상태 / 조정':'정산 생성'} onClose={()=>onClose()}><form onSubmit={save}>{!settlement?<><label>매장<select value={storeId} onChange={e=>setStoreId(e.target.value)} required>{state.stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="form-grid"><label>시작일<input type="date" value={start} onChange={e=>setStart(e.target.value)} required/></label><label>종료일<input type="date" value={end} min={start} onChange={e=>setEnd(e.target.value)} required/></label>{(['franchiseFee','platformFee','otherFee'] as const).map((key,i)=><label key={key}>{['가맹수수료','플랫폼비','기타비용'][i]}<input type="number" min="0" step="1" value={policy[key]} onChange={e=>setPolicy({...policy,[key]:Number(e.target.value)})}/></label>)}</div><p className="muted small">계약별 비용 정책을 입력하세요. 초안 정산으로 생성되며 확정 전 검토가 필요합니다.</p></>:<label>정산상태<select value={status} onChange={e=>setStatus(e.target.value)}>{['DRAFT','CONFIRMED','SCHEDULED','PAID','CANCELLED'].map((s,i)=><option key={s} value={s}>{['정산중','확정','지급예정','지급완료','취소'][i]}</option>)}</select></label>}<label>조정금액<input type="number" step="1" value={adjustment} onChange={e=>setAdjustment(Number(e.target.value))}/></label>{settlement&&<label>변경 사유<textarea value={memo} onChange={e=>setMemo(e.target.value)} rows={3}/></label>}{error&&<ErrorState message={error}/>}<button className="button" disabled={busy||!storeId}>정산 저장</button></form></Modal>;
}
