'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { LayoutDashboard, Store, ChartNoAxesCombined, Package, Boxes, ClipboardList, Wallet, Megaphone, MessageCircle, Bell, Sparkles, MoreHorizontal, LogOut, Menu, X } from 'lucide-react';
import { useApp, useData } from './provider';
import { ErrorState, Skeleton, TteungeumOnLogo } from './ui';
import { isHq } from '@/services/service';
const hqLinks=[['','대시보드',LayoutDashboard],['stores','매장관리',Store],['sales','매출관리',ChartNoAxesCombined],['products','상품관리',Package],['inventory','재고관리',Boxes],['orders','발주관리',ClipboardList],['settlements','정산관리',Wallet],['notices','공지사항',Megaphone],['support','문의관리',MessageCircle]] as const;
const storeLinks=[['','대시보드',LayoutDashboard],['sales','매출',ChartNoAxesCombined],['inventory','재고',Boxes],['reorder','자동발주',Sparkles],['orders','발주내역',ClipboardList],['ai','뜬금AI',Sparkles],['settlements','정산',Wallet],['notices','본사공지',Megaphone],['support','본사문의',MessageCircle],['more','더보기',MoreHorizontal]] as const;
export function NotificationBell(){const {state,session}=useData();const count=isHq(session)?state.orders.filter(o=>o.status==='REQUESTED').length:state.notifications.filter(n=>n.storeId===session.storeId&&!n.read).length;return <Link className="notification-bell" href={isHq(session)?'/hq/orders':'/store/notifications'} aria-label={isHq(session)?`발주대기 ${count}건`:`알림 ${count}개 미읽음`}><Bell size={21}/>{count>0&&<span>{count}</span>}</Link>;}
export function StoreSwitcher(){const {state,session}=useData();const store=state.stores.find(s=>s.id===session.storeId);return <span className="store-switcher"><Store size={16}/>{isHq(session)?'전체 매장':store?.name}</span>;}
export function Sidebar({hq,onNavigate}:{hq:boolean;onNavigate:()=>void}){const path=usePathname(),{logout}=useData(),router=useRouter(),root=hq?'/hq':'/store';return <><Link href={root} className="sidebar-brand" onClick={onNavigate}><TteungeumOnLogo/></Link><p className="sidebar-label">{hq?'본사 워크스페이스':'내 매장 워크스페이스'}</p><nav aria-label="주 메뉴">{(hq?hqLinks:storeLinks).map(([key,label,Icon])=>{const href=`${root}${key?`/${key}`:''}`,active=key?path.startsWith(href):path===root;return <Link href={href} key={key} className={`nav-link ${active?'selected':''}`} onClick={onNavigate} aria-current={active?'page':undefined}><Icon size={19}/>{label}</Link>;})}</nav><div className="sidebar-bottom"><div className="demo-label">DEMO · Mock 서비스</div><button className="nav-link" onClick={async()=>{await logout();router.replace('/login');}}><LogOut size={18}/>로그아웃</button></div></>;}
export function MobileNav(){const path=usePathname();const links=[['','홈',LayoutDashboard],['sales','매출',ChartNoAxesCombined],['inventory','재고',Boxes],['reorder','발주',ClipboardList],['more','더보기',MoreHorizontal]] as const;return <nav className="mobile-nav" aria-label="모바일 하단 메뉴">{links.map(([key,label,Icon])=>{const href=`/store${key?`/${key}`:''}`,active=key?path.startsWith(href)||key==='reorder'&&path.startsWith('/store/orders'):path==='/store';return <Link key={key} href={href} className={active?'selected':''} aria-current={active?'page':undefined}><Icon size={21}/><span>{label}</span></Link>;})}</nav>;}
export function AppShell({area,children}:{area:'hq'|'store';children:React.ReactNode}){
 const app=useApp(),router=useRouter(),[menu,setMenu]=useState(false);
 const authorized=!!app.session&&(area==='hq'?isHq(app.session):!isHq(app.session));
 useEffect(()=>{if(app.ready&&!app.error){if(!app.session)router.replace('/login');else if(!authorized)router.replace(isHq(app.session)?'/hq':'/store');}},[app.ready,app.session,app.error,authorized,router]);
 if(app.error)return <ErrorState message={app.error}/>;if(!app.ready||!app.state||!authorized)return <Skeleton/>;
 return <div className={`app-shell ${area==='store'?'store-shell':''}`}><aside className={`sidebar ${menu?'opened':''}`}><button className="sidebar-close icon-button" aria-label="메뉴 닫기" onClick={()=>setMenu(false)}><X/></button><Sidebar hq={area==='hq'} onNavigate={()=>setMenu(false)}/></aside>{menu&&<button className="menu-overlay" aria-label="메뉴 닫기" onClick={()=>setMenu(false)}/>}<div className="workspace"><header className="topbar"><div className="topbar-left"><button className="menu-button icon-button" aria-label="메뉴 열기" onClick={()=>setMenu(true)}><Menu/></button><StoreSwitcher/></div><div className="topbar-right"><span className="demo-pill">데모</span><NotificationBell/><span className="avatar">{app.session?.profile.name.slice(0,1)}</span><span className="user-name">{app.session?.profile.name} 님</span></div></header><main className="content">{children}</main><footer className="workspace-footer">뜬금ON V1 · 데모 데이터 · 실제 결제 또는 발주 전송 없음</footer></div>{area==='store'&&<MobileNav/>}</div>;
}
