'use client';
import { useState } from 'react';
import { useData } from './provider';
import { ErrorState, Modal } from './ui';
import type { Store } from '@/types/domain';
export function StoreForm({store,onClose}:{store:Store;onClose:()=>void}){
 const {state,execute,busy}=useData(),[draft,setDraft]=useState(store),[userId,setUserId]=useState(''),[role,setRole]=useState<'STORE_OWNER'|'STORE_MANAGER'|'STAFF'>('STORE_OWNER'),[memberActive,setMemberActive]=useState(true),[error,setError]=useState(''),[feedback,setFeedback]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();try{await execute({type:'store',store:draft});onClose();}catch(e){setError(e instanceof Error?e.message:'저장 실패');}}
 async function connect(){try{await execute({type:'membership',storeId:store.id,userId,role,active:memberActive});setFeedback('매장 계정 연결을 저장했습니다.');}catch(e){setError(e instanceof Error?e.message:'연결 실패');}}
 const exists=state.stores.some(s=>s.id===store.id);
 return <Modal title="매장 상세 / 수정" onClose={onClose}><form onSubmit={save}><div className="form-grid">{(['code','name','owner','phone','businessNumber','address','addressDetail','openedAt'] as const).map((key,i)=><label key={key}>{['매장코드','매장명','점주명','전화번호','사업자번호','주소','상세주소','개점일'][i]}<input type={key==='openedAt'?'date':'text'} value={draft[key]||''} required={key==='code'||key==='name'} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label>운영 형태<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as Store['type']})}><option>직영</option><option>가맹</option></select></label><label>운영상태<select value={draft.active?'ACTIVE':'INACTIVE'} onChange={e=>setDraft({...draft,active:e.target.value==='ACTIVE'})}><option value="ACTIVE">운영중</option><option value="INACTIVE">운영중지</option></select></label></div>{error&&<ErrorState message={error}/>}<button className="button" disabled={busy}>매장 저장</button></form>{exists&&<section className="mt"><h3>점주 / 매장 계정 연결</h3><div className="form-grid mt"><label>기존 계정<select value={userId} onChange={e=>setUserId(e.target.value)}><option value="">계정 선택</option>{state.profiles.filter(p=>!['SUPER_ADMIN','HQ_ADMIN','HQ_MANAGER'].includes(p.role)).map(p=><option value={p.id} key={p.id}>{p.name} · {p.email}</option>)}</select></label><label>매장 역할<select value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="STORE_OWNER">점주</option><option value="STORE_MANAGER">매니저</option><option value="STAFF">직원</option></select></label><label>연결 상태<select value={memberActive?'active':'inactive'} onChange={e=>setMemberActive(e.target.value==='active')}><option value="active">활성</option><option value="inactive">해제</option></select></label></div><button className="button secondary mt" disabled={!userId||busy} onClick={()=>void connect()}>계정 연결 저장</button><p className="muted small mt">계정의 시스템 역할은 최고관리자가 별도로 설정합니다. 매장 역할만으로 본사 권한을 얻을 수 없습니다.</p>{feedback&&<p role="status" className="positive">{feedback}</p>}<div className="mt">{state.storeMembers.filter(m=>m.storeId===store.id).map(m=><p key={m.id} className="muted small">{state.profiles.find(p=>p.id===m.profileId)?.email} · {m.role}</p>)}</div></section>}</Modal>;
}
