'use client';
import Link from 'next/link';
import { useEffect, useId, useRef } from 'react';
import { X, PackageOpen, AlertCircle, ChevronRight } from 'lucide-react';
import { money, number, orderLabels } from '@/lib/calculations';
import type { OrderStatus } from '@/types/domain';

export function TteungeumOnLogo(){return <span className="logo">뜬금<span>ON</span><small>매장을 더 똑똑하게 ON</small></span>;}
export function Money({value}:{value:number}){return <span className="tabular-nums">{money(value)}</span>;}
export function PageHeader({title,description,action}:{title:string;description?:string;action?:React.ReactNode}){return <div className="page-heading"><div><p className="eyebrow">TTEUNGEUM ON</p><h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{action}</div>;}
export function KpiCard({label,value,hint,positive}:{label:string;value:React.ReactNode;hint?:string;positive?:boolean}){return <article className="kpi"><p>{label}</p><strong>{value}</strong>{hint&&<small className={positive?'positive':'muted'}>{hint}</small>}</article>;}
export function StatusBadge({status}:{status:string}){const label=orderLabels[status as OrderStatus]||status;const tone=['품절','부족','취소','CANCELLED'].includes(status)?'danger':['주의','승인대기','REQUESTED','접수','정산중'].includes(status)?'warning':['정상','배송완료','DELIVERED','지급완료','답변완료','판매중'].includes(status)?'success':'blue';return <span className={`badge ${tone}`}>{label}</span>;}
export function FilterChip({active,children,onClick}:{active:boolean;children:React.ReactNode;onClick:()=>void}){return <button className={`chip ${active?'active':''}`} aria-pressed={active} onClick={onClick}>{children}</button>;}
export function SearchInput({value,onChange,placeholder='검색'}:{value:string;onChange:(value:string)=>void;placeholder?:string}){return <input type="search" aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)} className="search"/>;}
export function Panel({title,href,children}:{title:string;href?:string;children:React.ReactNode}){return <section className="panel"><div className="panel-heading"><h2>{title}</h2>{href&&<Link className="text-link" href={href}>전체 보기 <ChevronRight size={14}/></Link>}</div>{children}</section>;}
export function EmptyState({title='표시할 항목이 없습니다.',description,action}:{title?:string;description?:string;action?:React.ReactNode}){return <div className="empty"><PackageOpen size={32}/><h3>{title}</h3>{description&&<p>{description}</p>}{action}</div>;}
export function ErrorState({message}:{message:string}){return <div className="error" role="alert"><AlertCircle size={18}/>{message}</div>;}
export function Skeleton(){return <div className="loading" role="status"><div className="skeleton"/><p>매장 정보를 불러오고 있어요.</p></div>;}
export function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),titleId=useId();
 useEffect(()=>{const element=dialog.current;const previous=document.activeElement as HTMLElement|null;element?.showModal();return()=>{element?.close();previous?.focus();};},[]);
 return <dialog ref={dialog} className="modal" aria-labelledby={titleId} onCancel={e=>{e.preventDefault();onClose();}}><div className="modal-heading"><h2 id={titleId}>{title}</h2><button className="icon-button" onClick={onClose} aria-label="닫기"><X size={22}/></button></div>{children}</dialog>;
}
export function ConfirmDialog({title,description,onConfirm,onClose,busy}:{title:string;description:string;onConfirm:()=>void;onClose:()=>void;busy:boolean}){return <Modal title={title} onClose={()=>{if(!busy)onClose();}}><p className="muted">{description}</p><div className="actions"><button className="button secondary" onClick={onClose} disabled={busy}>돌아가기</button><button className="button" onClick={onConfirm} disabled={busy}>{busy?'처리 중…':'확인'}</button></div></Modal>;}
export function QuantityControl({value,onChange,min=1,label='수량',disabled=false}:{value:number;onChange:(n:number)=>void;min?:number;label?:string;disabled?:boolean}){return <div className="quantity"><button aria-label={`${label} 감소`} disabled={disabled||value<=min} onClick={()=>onChange(Math.max(min,value-1))}>−</button><input aria-label={label} type="number" min={min} max={99999} value={value} disabled={disabled} onChange={e=>{const n=Number(e.target.value);if(Number.isSafeInteger(n)&&n>=min&&n<=99999)onChange(n);}}/><button aria-label={`${label} 증가`} disabled={disabled||value>=99999} onClick={()=>onChange(value+1)}>+</button></div>;}
export function DataTable<T>({rows,columns,keyOf,empty='검색 결과가 없습니다.'}:{rows:T[];columns:{label:string;render:(row:T)=>React.ReactNode}[];keyOf:(row:T)=>string;empty?:string}){if(!rows.length)return <EmptyState title={empty}/>;return <><div className="desktop-table"><table><thead><tr>{columns.map(c=><th key={c.label}>{c.label}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={keyOf(r)}>{columns.map(c=><td key={c.label}>{c.render(r)}</td>)}</tr>)}</tbody></table></div><div className="mobile-cards">{rows.map(r=><article className="record-card" key={keyOf(r)}>{columns.map(c=><div className="record-row" key={c.label}><span>{c.label}</span><div>{c.render(r)}</div></div>)}</article>)}</div></>;}
export function ChartCard({title,points,kind='line'}:{title:string;points:{label:string;value:number}[];kind?:'line'|'bar'}){
 const max=Math.max(1,...points.map(p=>p.value)),width=600,height=200,pad=24,plot=points.map((p,i)=>({x:pad+i*(width-pad*2)/Math.max(1,points.length-1),y:height-pad-(p.value/max)*(height-pad*2)}));
 return <Panel title={title}>{points.length?<><div className="chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${title}: ${points.map(p=>`${p.label} ${money(p.value)}`).join(', ')}`}><title>{title}</title>{[.25,.5,.75,1].map(n=><line key={n} x1={pad} x2={width-pad} y1={height-pad-n*(height-pad*2)} y2={height-pad-n*(height-pad*2)} stroke="#e2e8f0" strokeDasharray="4 4"/>)}{kind==='line'?<><polyline fill="none" stroke="#2563eb" strokeWidth="3" strokeLinejoin="round" points={plot.map(p=>`${p.x},${p.y}`).join(' ')}/>{plot.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="3.5" fill="#2563eb"><title>{points[i].label}: {money(points[i].value)}</title></circle>)}</>:plot.map((p,i)=><rect key={i} x={p.x-8} y={p.y} width="16" height={height-pad-p.y} rx="3" fill="#2563eb"><title>{points[i].label}: {money(points[i].value)}</title></rect>)}</svg></div><div className="chart-labels">{points.filter((_,i)=>points.length<=8||i%Math.ceil(points.length/6)===0||i===points.length-1).map(p=><span key={p.label}>{p.label}</span>)}</div><details className="chart-data"><summary>그래프 데이터 보기</summary>{points.map(p=><div className="list-row" key={p.label}><span>{p.label}</span><span>{number(p.value)}원</span></div>)}</details></>:<EmptyState/>}</Panel>;
}
