import { Client } from 'pg';
import { readFileSync, readdirSync } from 'node:fs';
import assert from 'node:assert/strict';
import { projectWorkspace } from '../src/repositories/workspace';
import { randomUUID } from 'node:crypto';
async function main(){
const base=process.env.TEST_DATABASE_URL||'postgres://postgres:local_test_only@127.0.0.1:55432/postgres';
if(!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw new Error('DB tests only run on an isolated local database.');
const admin=new Client({connectionString:base});await admin.connect();
const database=`tteungeum_test_${Date.now()}`;await admin.query(`create database ${database}`);
const url=new URL(base);url.pathname=`/${database}`;
const db=new Client({connectionString:url.toString()});await db.connect();
const hq=randomUUID(),a=randomUUID(),b=randomUUID(),staff=randomUUID(),inactive=randomUUID(),storeA=randomUUID(),storeB=randomUUID(),category=randomUUID(),supplier=randomUUID(),product=randomUUID();
let passed=0;
async function as(user:string,run:()=>Promise<void>){await db.query('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);try{await run();}finally{await db.query('reset role');await db.query("select set_config('request.jwt.claim.sub','',false)");}}
async function rpc<T=unknown>(name:string,args:unknown[]=[]):Promise<T>{return (await db.query(`select public.${name}(${args.map((_,i)=>`$${i+1}`).join(',')}) result`,args.map(value=>Array.isArray(value)?JSON.stringify(value):value))).rows[0].result as T;}
async function check(label:string,run:()=>Promise<void>){await run();passed++;console.log(`PASS ${label}`);}
async function stock(){return Number((await db.query('select quantity from inventories where store_id=$1 and product_id=$2',[storeA,product])).rows[0].quantity);}
try{
 // Stub only the Supabase auth contract. Database transactions and RLS are real PostgreSQL.
 await db.query(`do $$ begin if not exists(select 1 from pg_roles where rolname='anon') then create role anon nologin;end if;if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin;end if;end$$;
 create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb not null default '{}');
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to anon,authenticated;grant execute on function auth.uid() to authenticated;`);
 for(const file of readdirSync('supabase/migrations').sort())await db.query(readFileSync(`supabase/migrations/${file}`,'utf8'));
 for(const [id,role] of [[hq,'HQ_ADMIN'],[a,'STORE_OWNER'],[b,'STORE_OWNER'],[staff,'STAFF'],[inactive,'STORE_OWNER']]){
 await db.query('insert into auth.users(id,email) values($1,$2)',[id,`${id}@test.invalid`]);await db.query('update profiles set role=$1,active=$2 where id=$3',[role,id!==inactive,id]);}
 await db.query("insert into stores(id,code,name) values($1,'A','매장A'),($2,'B','매장B')",[storeA,storeB]);
 await db.query("insert into store_memberships(user_id,store_id,store_role) values($1,$2,'STORE_OWNER'),($3,$4,'STORE_OWNER'),($5,$2,'STAFF'),($6,$2,'STORE_OWNER')",[a,storeA,b,storeB,staff,inactive]);
 await db.query("insert into categories(id,name) values($1,'커피');",[category]);await db.query("insert into suppliers(id,code,name) values($1,'HQ','본사')",[supplier]);
 const saveProduct={id:product,sku:'TEST-001',name:'테스트 커피',categoryId:category,supplierId:supplier,cost:1000,supplyPrice:1500,price:3000,safetyStock:5,reorderQuantity:20,recommendedStock:30,active:true};
 await check('HQ 상품 생성·가격수정 감사로그',async()=>as(hq,async()=>{await rpc('manage_entity',['product',saveProduct]);await rpc('manage_entity',['product',{...saveProduct,price:3500}]);const logs=await db.query('select * from audit_logs where entity_id=$1 and action=\'UPDATE\'',[product]);assert.equal(logs.rows[0].before_data.sale_price,3000);assert.equal(logs.rows[0].after_data.sale_price,3500);}));
 await check('직접 테이블 쓰기·helper 실행·점주 HQ 작업 차단',async()=>as(a,async()=>{await assert.rejects(db.query("update products set sale_price=1"));await assert.rejects(rpc('manage_entity',['product',saveProduct]));await assert.rejects(rpc('move_inventory',[storeA,product,100,'ADJUSTMENT',null,'bypass']));await assert.rejects(rpc('manage_entity',['membership',{storeId:storeB,userId:a,role:'STORE_OWNER'}]));}));
 await check('매장 A는 B의 재고·정산·매출·발주·문의 조회/수정 불가',async()=>as(a,async()=>{assert.equal((await db.query('select * from stores')).rows.length,1);assert.equal((await db.query('select * from inventories where store_id=$1',[storeB])).rows.length,0);for(const table of ['sales','purchase_orders','settlements','inquiries','inventory_movements'])assert.equal((await db.query(`select * from ${table} where store_id=$1`,[storeB])).rows.length,0);await assert.rejects(rpc('adjust_inventory',[storeB,product,1,'wrong store']));}));
 await check('STAFF 제한·비활성 프로필·익명 접근 차단',async()=>{await as(staff,async()=>{await assert.rejects(rpc('adjust_inventory',[storeA,product,1,'staff']));await assert.rejects(rpc('create_order',[storeA,[{productId:product,quantity:1}],'staff','staff-key-1','MANUAL']));});await as(inactive,async()=>{assert.equal((await db.query('select * from inventories')).rows.length,0);await assert.rejects(rpc('adjust_inventory',[storeA,product,1,'inactive']));});await db.query('set role anon');await assert.rejects(db.query('select * from products'));await db.query('reset role');});
 await check('재고조정·음수 재고 차단·movement 기록',async()=>as(a,async()=>{await rpc('adjust_inventory',[storeA,product,30,'초기 입고']);assert.equal(await stock(),30);await assert.rejects(rpc('adjust_inventory',[storeA,product,-31,'음수']));assert.equal(await stock(),30);}));
 const salePayload={idempotencyKey:'sale-test-key',externalPosId:'pos-test-1',items:[{productId:product,quantity:2}],soldAt:'2026-10-05T15:00:00Z'};let saleId='';
 await check('매출 원자적 등록·재고 차감·멱등성·다른 요청 충돌',async()=>as(a,async()=>{saleId=await rpc<string>('create_sale',[storeA,salePayload]);assert.equal(await stock(),28);assert.equal(await rpc('create_sale',[storeA,salePayload]),saleId);assert.equal(await stock(),28);await assert.rejects(rpc('create_sale',[storeA,{...salePayload,items:[{productId:product,quantity:3}]}]));await assert.rejects(rpc('create_sale',[storeA,{idempotencyKey:'insufficient-key',items:[{productId:product,quantity:29}]}]));assert.equal((await db.query('select count(*) from sales')).rows[0].count,'1');}));
 await check('매출 취소 재고복원·중복 취소 안전',async()=>as(a,async()=>{await rpc('cancel_sale',[saleId]);assert.equal(await stock(),30);await rpc('cancel_sale',[saleId]);assert.equal(await stock(),30);}));
 await check('Asia/Seoul 날짜경계와 판매건수 집계',async()=>as(a,async()=>{await rpc('create_sale',[storeA,{...salePayload,idempotencyKey:'korea-boundary-key',externalPosId:'pos-boundary'}]);const view=await rpc<{sales:{date:string;order_count:number}[]}>('workspace_snapshot',['2026-10-06','2026-10-06']);assert.equal(view.sales[0].date,'2026-10-06');assert.equal(view.sales[0].order_count,1);const report=projectWorkspace(await rpc('workspace_snapshot',['2026-10-06','2026-10-06','2026-10-06','2026-10-06']));assert.deepEqual(report.reportPeriod,{start:'2026-10-06',end:'2026-10-06'});assert.equal(report.productTotals?.[0].quantity,2);assert.equal(report.productTotals?.[0].amount,7000);assert.equal(report.periodHours?.[0].hour,0);assert.equal(report.periodHours?.[0].total,7000);}));
 let order='';
 await check('발주 생성·중복 요청 안전·미입고 상품 자동추천 차단',async()=>as(a,async()=>{order=await rpc<string>('create_order',[storeA,[{productId:product,quantity:10}],'test','order-test-key','MANUAL']);assert.equal(await rpc('create_order',[storeA,[{productId:product,quantity:10}],'test','order-test-key','MANUAL']),order);await rpc('adjust_inventory',[storeA,product,-25,'추천 기준']);assert.equal(await rpc('suggest_orders',[storeA,'suggest-test-block']),null);await assert.rejects(rpc('create_order',[storeA,[{productId:product,quantity:20}],'test','auto-test-key','AUTO_SUGGESTED']));}));
 await check('본사 승인→발주→배송→입고·중복 입고 차단',async()=>as(hq,async()=>{for(const status of ['APPROVED','ORDERED','SHIPPED','RECEIVED'])await rpc('change_order_status',[order,status]);assert.equal(await stock(),13);await assert.rejects(rpc('change_order_status',[order,'RECEIVED']));assert.equal(await stock(),13);const items=await db.query('select received_quantity from purchase_order_items where purchase_order_id=$1',[order]);assert.equal(items.rows[0].received_quantity,10);}));
 await check('자동발주 제안 생성·동시 중복 제안 차단',async()=>as(a,async()=>{await rpc('adjust_inventory',[storeA,product,-10,'추천 기준']);const id=await rpc('suggest_orders',[storeA,'suggest-real-key']);assert.ok(id);assert.equal(await rpc('suggest_orders',[storeA,'suggest-real-key']),id);assert.equal(await rpc('suggest_orders',[storeA,'suggest-second-key']),null);const o=await db.query('select * from purchase_orders where id=$1',[id]);assert.equal(o.rows[0].order_type,'AUTO_SUGGESTED');}));
 await check('정산 생성·기간 겹침 차단·본사 확정·점주 자기 정산만',async()=>{await as(hq,async()=>{const id=await rpc<string>('generate_settlement',[storeA,'2026-10-01','2026-10-31',{franchiseFee:100,platformFee:50,otherFee:0,adjustment:10}]);await assert.rejects(rpc('generate_settlement',[storeA,'2026-10-10','2026-11-10',{}]));await rpc('update_settlement',[id,'CONFIRMED',20,'정책 검토']);await rpc('generate_settlement',[storeB,'2026-10-01','2026-10-31',{}]);});await as(a,async()=>{const s=await db.query('select * from settlements');assert.equal(s.rows.length,1);assert.equal(s.rows[0].store_id,storeA);await assert.rejects(rpc('generate_settlement',[storeB,'2026-12-01','2026-12-31',{}]));});});
 await check('프로필 자가승격 차단·RLS 모든 테이블 활성화',async()=>as(a,async()=>{await assert.rejects(db.query("update profiles set role='SUPER_ADMIN' where id=$1",[a]));await assert.rejects(rpc('manage_entity',['profile',{id:a,role:'SUPER_ADMIN'}]));assert.equal((await db.query("select relname from pg_class where relnamespace='public'::regnamespace and relkind='r' and not relrowsecurity")).rows.length,0);}));
 // Separate connections exercise row locks rather than relying on UI button state.
 await check('동시 POS 요청은 한 번만 저장·차감',async()=>{
 const connections=[new Client({connectionString:url.toString()}),new Client({connectionString:url.toString()})];await Promise.all(connections.map(c=>c.connect()));
 try{await as(a,async()=>{await rpc('adjust_inventory',[storeA,product,20,'동시성 준비']);});const before=await stock();const payload={idempotencyKey:'concurrent-key',items:[{productId:product,quantity:2}]};
 for(const c of connections){await c.query('set role authenticated');await c.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);}
 const results=await Promise.all(connections.map(c=>c.query('select create_sale($1,$2) id',[storeA,payload])));assert.equal(results[0].rows[0].id,results[1].rows[0].id);assert.equal(await stock(),before-2);
 }finally{await Promise.all(connections.map(c=>c.end()));}
 });
 await check('DB 스냅샷을 기존 UI 타입으로 변환 (가짜 수치 없음)',async()=>as(hq,async()=>{const data=projectWorkspace(await rpc('workspace_snapshot',['2026-10-01','2026-10-31']));assert.equal(data.production,true);assert.equal(data.stores.length,2);assert.equal(data.products[0].sku,'TEST-001');assert.ok(data.sales.length);assert.equal(data.sales.reduce((n,s)=>n+s.orderCount,0),2);assert.ok(data.orders.some(o=>o.status==='DELIVERED'));assert.equal(data.settlements.filter(s=>s.status==='확정').length,1);}));

 await check('본사 매장 등록·수정·비활성화·계정 연결 감사기록',async()=>as(hq,async()=>{const store=randomUUID();await rpc('manage_entity',['store',{id:store,code:'C',name:'매장C',status:'ACTIVE'}]);await rpc('manage_entity',['membership',{storeId:store,userId:b,role:'STORE_OWNER',active:true}]);await rpc('manage_entity',['store',{id:store,code:'C',name:'매장C 수정',status:'INACTIVE'}]);const row=(await db.query('select * from stores where id=$1',[store])).rows[0];assert.equal(row.status,'INACTIVE');assert.equal(row.name,'매장C 수정');assert.ok((await db.query('select * from audit_logs where entity_id=$1',[store])).rows.length>=2);}));
 await check('장바구니 발주·비우기 원자성·네트워크 재시도 멱등성',async()=>as(a,async()=>{await rpc('manage_entity',['cart',{storeId:storeA,items:[{productId:product,quantity:4}]}]);const id=await rpc('submit_cart',[storeA,'cart','atomic-cart-key','MANUAL']);assert.equal((await db.query('select * from order_carts')).rows.length,0);await rpc('manage_entity',['cart',{storeId:storeA,items:[{productId:product,quantity:2}]}]);assert.equal(await rpc('submit_cart',[storeA,'cart','atomic-cart-key','MANUAL']),id);assert.equal((await db.query('select * from order_carts')).rows[0].items[0].quantity,2);await assert.rejects(rpc('submit_cart',[storeA,'changed','atomic-cart-key','MANUAL']));await assert.rejects(rpc('create_sale',[storeA,{idempotencyKey:'missing-items-key'}]));}));
 await check('동시 동일 입고는 1회 성공·1회 거절·재고 1회 증가',async()=>{
 let order='';await as(a,async()=>{order=await rpc('create_order',[storeA,[{productId:product,quantity:4}],'concurrent','concurrent-receipt-key','MANUAL']);});await as(hq,async()=>{for(const status of ['APPROVED','ORDERED','SHIPPED'])await rpc('change_order_status',[order,status]);});const before=await stock();const cs=[new Client({connectionString:url.toString()}),new Client({connectionString:url.toString()})];await Promise.all(cs.map(c=>c.connect()));try{for(const c of cs){await c.query('set role authenticated');await c.query("select set_config('request.jwt.claim.sub',$1,false)",[hq]);}const result=await Promise.allSettled(cs.map(c=>c.query("select change_order_status($1,'RECEIVED')",[order])));assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal(result.filter(r=>r.status==='rejected').length,1);assert.equal(await stock(),before+4);}finally{await Promise.all(cs.map(c=>c.end()));}
 });
 await check('공지 게시·중지 RLS와 문의 답변·알림 읽음',async()=>{
 let notice='';const ticket=randomUUID();await as(hq,async()=>{notice=await rpc('manage_entity',['notice',{title:'공지 테스트',body:'내용',published:true}]);});await as(a,async()=>{assert.equal((await db.query('select * from notices')).rows.length,1);await rpc('manage_entity',['readNotice',{id:notice}]);await rpc('manage_entity',['ticket',{id:ticket,storeId:storeA,category:'배송',title:'배송 질문',body:'문의내용'}]);});await as(hq,async()=>{await rpc('manage_entity',['noticeUpdate',{id:notice,title:'공지 테스트',body:'내용',published:false}]);await rpc('manage_entity',['ticketReply',{id:ticket,answer:'배송 안내',status:'ANSWERED'}]);});await as(a,async()=>{assert.equal((await db.query('select * from notices')).rows.length,0);await assert.rejects(rpc('manage_entity',['readNotice',{id:notice}]));assert.equal((await db.query('select * from inquiries where id=$1',[ticket])).rows[0].response,'배송 안내');const n=(await db.query('select * from notifications where read_at is null')).rows[0];assert.ok(n);await rpc('manage_entity',['readNotification',{id:n.id}]);assert.ok((await db.query('select read_at from notifications where id=$1',[n.id])).rows[0].read_at);});
 });
 console.log(`${passed} PostgreSQL integration checks passed. Remote Supabase Auth is not exercised by this test.`);
}finally{await db.end();await admin.query(`drop database ${database}`);await admin.end();}

}
void main().catch(error=>{console.error(error);process.exitCode=1;});
